### ISSUE TITLE
add editor to edit the detail infomation of image

### ISSUE THREAD

**Issue by piaolingxue** [atc-/docker-registry-ui#110]
When run an image in docker-registry-web, I have to search google to find how to use the image. If I can see image info in docker-registry-web, That's will be awesome.

**Comment by rogierlommers** [comment]
How do you add info to the `description` field in a way that atcol/docker-registry-ui will show it?

**Comment by atc-** [comment]
This is part of the metadata returned by the registry. Presumably you could populate it using [labels](https://docs.docker.com/reference/builder/) in a dockerfile?
