### ISSUE TITLE
Allow to proxy registry information.

### ISSUE THREAD

**Issue by richtera** [atc-/docker-registry-ui#134]
A registry may be accessible locally using --link docker_registry:registry -e REG1=http://registry:5000/v1 but should be published under the nginx accessible URL (i.e. https://registry.{somedomain})
Maybe there should be a 
REG1=http://registry:5000/v1 REG1_PUBLISHED=https://registry.{somedomain}/v1
All this would do is return the right URL when looking at a version and it's docker pull.

**Comment by atc-** [comment]
This seems similar to the aliasing requirement, raised here: #122.

**Comment by richtera** [comment]
Yes this is the same. Along with it the password should be hideable :)
