### ISSUE TITLE
Storage S3

### ISSUE THREAD

**Issue by berrywira** [atc-/docker-registry-ui#148]
Hi There!

How to connect docker-registry-frontend with docker registry storage S3, can I?

**Comment by atc-** [comment]
For what purpose? Can you explain your use case(s) a little further please?

**Comment by berrywira** [comment]
Yes, 
I have docker registry connected storage S3. and I want use registry ui for frontend. all repo/image on s3 can visible in docker registry ui. Thanks

**Comment by atc-** [comment]
Which version of Docker Registry?

**Comment by berrywira** [comment]
Sorry for long respon,  Docker registry V2.

**Comment by atc-** [comment]
That's in the works :) See #141
